### ISSUE TITLE
[Request] Handle Storage

### ISSUE THREAD

**Issue by gagdiez** [near/near-social-db-sdk#2]
It is common that, after setting things in the SocialDB contract, there is payed storage that is unnused, and the user needs to claim them back.

Knowing how much storage is being used and how much money can be claimed back was a feature of the `VM` that most probably we need to port

**Comment by shelegdmitriy** [comment]
As far as we don't plan to extend this module anymore in favour of this one https://github.com/NEARBuilders/near-social-js (which does the same) I found this two tasks which should cover this request:

- https://github.com/NEARBuilders/near-social-js/issues/13;
- https://github.com/NEARBuilders/near-social-js/issues/14
